# Generated by Django 3.2.10 on 2023-04-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postcreator', '0004_alter_post_created_at'),
        ('postviewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ViwedPost',
            new_name='ViewedPost',
        ),
    ]
