# Generated by Django 3.2.10 on 2023-04-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcreator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tag',
            new_name='name',
        ),
        migrations.AddField(
            model_name='tags',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Tag_weight',
        ),
    ]
