# Generated by Django 3.2.10 on 2023-04-30 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcreator', '0005_auto_20230430_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_created=True, blank=True, default=datetime.datetime(2023, 5, 1, 1, 10, 25, 826806)),
        ),
    ]
